site_name: "PyEarth"
site_description: 'PyEarth'
site_author: 'Weiqiang Zhu'
repo_name: 'PyEarth'
repo_url: 'https://github.com/ai4eps/ai4eps.github.io/classes/pyearth'
nav:
    - Overview: README.md
    - Obspy:
      - Install packages: obspy/install.md
      - Download seismic data: obspy/seismic_waveform.ipynb
      - Realtime data streaming: obspy/animation_seedlink.ipynb
      - Signal processing: obspy/signal_processing.ipynb
    - Projection: projection.ipynb
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
