site_name: "AI4EPS"
site_url: "https://ai4eps.github.io/"
site_author: "Weiqiang Zhu"
site_description: ""

# Repository
repo_name: "AI4EPS"
repo_url: "https://github.com/ai4eps"

# Page tree
nav:
  - Home: README.md
  - Research: 
    - research.md
    - QuakeFlow: '!include ./QuakeFlow/mkdocs.yml'
    - DeepDenoiser: '!include ./DeepDenoiser/mkdocs.yml'
    - PhaseNet: '!include ./PhaseNet/mkdocs.yml'
    - GaMMA: '!include ./GaMMA/mkdocs.yml'
    - ADSeismic: '!include ./ADSeismic.jl/mkdocs.yml'
  - Teaching: 
    - teaching.md
    - PyEarth: '!include ./classes/pyearth/mkdocs.yml'
    - ML4Earth: '!include ./classes/ml4earth/mkdocs.yml'
  - Publication: publication.md
  - CV: cv.pdf


# Configuration
theme:
  name: "material"

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  # - minify:
  #     minify_html: true
  - mkdocs-jupyter:
      ignore_h1_titles: True
      ignore: ["ADSeismic/examples/*/*.ipynb", "ADSeismic/examples/*/*/*.ipynb"]
  - monorepo
  - bibtex:
      bib_file: "docs/publications.bib"
  - redirects:
      redirect_maps:
        'quakeflow': 'https://ai4eps.github.io/QuakeFlow' 
        'deepdenoiser': 'https://ai4eps.github.io/DeepDenoiser' 
        'phasenet': 'https://ai4eps.github.io/PhaseNet'
        'gamma': 'https://ai4eps.github.io/GaMMA'
        'adseismic': 'https://ai4eps.github.io/ADSeismic'
        'pyearth': 'https://ai4eps.github.io/PyEarth'
        'ml4earth': 'https://ai4eps.github.io/ML4Earth'

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-5P3JS5EJW8
