site_name: "AI4Earth"
site_url: "https://ai4earth.github.io/"
site_author: "Weiqiang Zhu"
site_description: ""

# Repository
repo_name: "AI4Earth"
repo_url: "https://github.com/ai4earth.github.io"
edit_uri: ""

# Page tree
nav:
  - Home: README.md
  - Research: 
    - Research.md
    - QuakeFlow: '!include ./QuakeFlow/mkdocs.yml'
    - DeepDenoiser: '!include ./DeepDenoiser/mkdocs.yml'
    - PhaseNet: '!include ./PhaseNet/mkdocs.yml'
    - GaMMA: '!include ./GaMMA/mkdocs.yml'
    - ADSeismic: '!include ./ADSeismic.jl/mkdocs.yml'
  - Teaching: 
    - Teaching.md
    - PyEarth: '!include ./classes/pyearth/mkdocs.yml'
  - Publication: Publication.md
  - CV: CV.pdf


# Configuration
theme:
  name: "material"

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  - mkdocs-jupyter:
      ignore: ["ADSeismic/examples/*/*.ipynb", "ADSeismic/examples/*/*/*.ipynb"]
  - monorepo
  - bibtex:
      bib_file: "docs/publications.bib"

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-5P3JS5EJW8