site_name: "ML4Earth"
site_description: 'Machine Learning for Earth Science'
site_author: 'Weiqiang Zhu'
repo_name: 'ML4Earth'
repo_url: 'https://github.com/ai4eps/classes/ml4earth'
nav:
    - Overview: README.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
